Do not wait for the whole steps to be run, or even successful to start the εxodus analysis
matrix-org/pipelines pull request #103
Opened 2020-10-22 16:07 UTC by bmarty

This PR is to avoid the εxodus not to be run if an unnecessary step fails, for instance see https://buildkite.com/matrix-dot-org/element-android/builds/484 :

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3940906/96899553-57283b80-1491-11eb-9a03-6f9df7920dcd.png">

But I'm really not confident to the changes I've made, because I do not know how to test the new pipeline.

Inspired from https://buildkite.com/docs/pipelines/dependencies

2020-10-22 16:17 UTC, richvdh requested changes

2020-10-22 16:17 UTC, richvdh commented on element-android/pipeline.yml
> +      key: "elementApp"
I think this needs to be in the parent object:

```suggestion
    key: "elementApp"
```

the same for the other two places below.

2020-10-23 13:54 UTC, richvdh commented on element-android/pipeline.yml
> +      depends_on: "elementApp"
```suggestion
    depends_on: "elementApp"
```

2020-10-23 13:59 UTC, richvdh commented on element-android/pipeline.yml
> +    key: "elementApp"
we should surely not have two steps with the same key?

```suggestion
    key: "gplay_debug"
```

2020-10-23 13:59 UTC, richvdh commented on element-android/pipeline.yml
> +    key: "elementApp"
```suggestion
    key: "gplay_release"
```

2020-10-23 13:59 UTC, richvdh commented on element-android/pipeline.yml
> +    depends_on: "elementApp"
```suggestion
    depends_on: 
      - gplay_debug
      - gplay_release
```

2020-10-23 14:09 UTC, richvdh approved these changes

2020-10-23 14:09 UTC, merged

2020-10-23 14:13 UTC, richvdh commented
hrm, I see, we do not run both build steps. I have merged this, but I don't know if it will work...

2020-10-23 14:15 UTC, richvdh commented
https://buildkite.com/docs/pipelines/dependencies#order-of-operations says:

> However, if the step you're dependent on is excluded from the build due to an if condition, the dependency will be ignored and the step that depends on it will run once any other dependencies are satisfied.

so hopefully this will do the right thing

2020-10-23 15:59 UTC, bmarty commented
Thanks for the update @richvdh, I had the same thinking path as yours reading the change :)